<!-- Header Area Start here -->
<header id="main_heading">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <nav class="navbar">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <i class="fa fa-navicon"></i>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav custom_nav text-right pull-right">
                            <li class="active"><a href="<?php echo $block->getBaseUrl() ?>">Home</a></li>
                            <li><a href="<?php echo $block->getBaseUrl() ?>#membership">Membership</a></li>
                            <li><a href="<?php echo $block->getBaseUrl() ?>#facilities">Facilities</a></li>
                            <li><a href="<?php echo $block->getBaseUrl() ?>#team">Team</a></li>
                            <li><a href="<?php echo $block->getBaseUrl() ?>#aboutus">About Us</a></li>
                            <li><a href="<?php echo $block->getBaseUrl() ?>#gallery">Gallery</a></li>
                            <li><a href="<?php echo $block->getBaseUrl() ?>#footer">Contact Us</a></li>
                            <li class="minicart-custom"><?php echo $this->getChildHtml('minicart') ?></li>
                        </ul>

                    </div>
                </nav>
            </div>
        </div>
    </div>
</header>