<!-- Preloader Area Start Here -->
<div class="preloader">
    <div class="spinner">
        <div class="dot1"></div>
        <div class="dot2"></div>
    </div>
</div>
<!-- Preloader Area End Here -->
<!-- Header Area Start here -->
<header id="main_heading">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <nav class="navbar">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <i class="fa fa-navicon"></i>
                        </button>
                        <a class="navbar-brand" href="#">
                            <img src="img/logo.png" alt="">
                        </a>
                    </div>
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav custom_nav text-right pull-right">
                            <li class="active"><a href="#home">Home</a></li>
                            <li><a href="#product">Product</a></li>
                            <!-- <li><a href="#shop">Shop</a></li> -->
                            <li><a href="#facilities">Facilities</a></li>
                            <li><a href="#team">Team</a></li>
                            <li><a href="#aboutus">About Us</a></li>
                            <li><a href="#gallery">Gallery</a></li>
                            <li><a href="#contact">Contact</a></li>
                        </ul>

                    </div>
                </nav>
            </div>
        </div>
    </div>
</header>